### ISSUE TITLE
New maintainer wanted

### ISSUE THREAD

**Issue by harti2006** [Rothamsted/neo4j-server-maven-plugin#11]
Hi @marco-brandizi,

would you be up to take over this project as a new maintainer? I'm not really interested anymore, because
* I haven't worked with Neo4J for ages
* I would nowadays solve the problem using Docker with [Testcontainers](https://www.testcontainers.org/)
* You are the only recent contributor to the project

I don't want to become a bottle neck in your development.

Best regards,
André

**Comment by marco-brandizi** [comment]
Hi @harti2006,

sorry for my late reply, this issue slipped through my messed-up inbox...

While you aren't my bottleneck (I use the fork when I have changes that haven't reached the main repo yet), I would be fine with taking over with managing the main repo. 

At least, I can maintain this good plugin until I move to something like Testcontainers too, which is something I'm considering (I'm undecided, cause that approach is more lightweight and more general, but it introduces Docker as pre-requirement, I've always liked the idea of making people able to quickly do clone/mvn/run!).

I've sent you a linkedIn invitation, together with contact details (I guess we need to exchange details like Maven central credentials).

Thanks! Marco.

**Comment by harti2006** [comment]
Awesome, let's continue discussion in the LinkedIn chat...
