### ISSUE TITLE
Inconvenient behavior with deleteDb set to false

### ISSUE THREAD

**Issue by arkanovicz** [Rothamsted/neo4j-server-maven-plugin#8]
When the database doesn't exist yet, and deleteDb is set to false, the plugin cannot connect to neo4j because it tries to use the password parameter instead of 'neo4j'.

There are several ways to circumvent the problem, like activating different maven profiles depending on whether or not the database file does exist or not, but using profiles requires to use external properties since maven user properties aren't available at the time of profiles activations. Since the database path itself is defined inside the pom, that's quite unpractical.

I guess the plugin could check the status of the database before starting neo4j. At least, for instance, if the database path doesn't exist yet, it should temporary set deleteDb to true, otherwise newcomers will always stumble on this issue. Or the plugin could always try to connect with neo4j/neo4j at first, or use another clever decision mechanism I'm unaware of...

**Comment by harti2006** [comment]
Thanks for reporting. I tested and can confirm the inconvenience. I will come up with a fix.

**Comment by marco-brandizi** [comment]
@arkanovicz I don't know if this is still relevant to you (sorry for the very long delay). Now it should be fixed. If you can, let me know if it works for you too, so I'll be able to close it.

**Comment by arkanovicz** [comment]
I'm sorry, I can't easily test it, now. But if it works for you, most probably the bug is fixed.
